// Date: 2015/04/12 15:55:15
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package gvcguns.client;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class GVCModelItemM134 extends ModelBase
{
  //fields
    ModelRenderer Shape1;
    ModelRenderer Shape2;
    ModelRenderer Shape3;
    ModelRenderer Shape4;
    ModelRenderer Shape5;
    ModelRenderer Shape6;
    ModelRenderer Shape7;
    ModelRenderer Shape8;
    ModelRenderer Shape9;
    ModelRenderer Shape10;
    ModelRenderer Shape11;
  
  public GVCModelItemM134()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      Shape1 = new ModelRenderer(this, 0, 0);
      Shape1.addBox(0F, 0F, 0F, 2, 5, 2);
      Shape1.setRotationPoint(0F, 0F, 0F);
      Shape1.setTextureSize(64, 32);
      Shape1.mirror = true;
      setRotation(Shape1, 0.1745329F, 0F, 0F);
      Shape2 = new ModelRenderer(this, 9, 0);
      Shape2.addBox(0F, 0F, 0F, 4, 4, 10);
      Shape2.setRotationPoint(-1F, 4F, -6F);
      Shape2.setTextureSize(64, 32);
      Shape2.mirror = true;
      setRotation(Shape2, 0F, 0F, 0F);
      Shape3 = new ModelRenderer(this, 0, 15);
      Shape3.addBox(-1.5F, -1.5F, 0F, 3, 3, 12);
      Shape3.setRotationPoint(1F, 6F, -18F);
      Shape3.setTextureSize(64, 32);
      Shape3.mirror = true;
      setRotation(Shape3, 0F, 0F, 0.7853982F);
      Shape4 = new ModelRenderer(this, 38, 0);
      Shape4.addBox(0F, 0F, 0F, 2, 2, 10);
      Shape4.setRotationPoint(-3F, 6F, -6F);
      Shape4.setTextureSize(64, 32);
      Shape4.mirror = true;
      setRotation(Shape4, 0F, 0F, 0F);
      Shape5 = new ModelRenderer(this, 38, 13);
      Shape5.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape5.setRotationPoint(-1F, 1F, -6F);
      Shape5.setTextureSize(64, 32);
      Shape5.mirror = true;
      setRotation(Shape5, 0F, 0F, 0F);
      Shape6 = new ModelRenderer(this, 38, 13);
      Shape6.addBox(0F, 0F, 0F, 1, 2, 1);
      Shape6.setRotationPoint(2F, 1F, -6F);
      Shape6.setTextureSize(64, 32);
      Shape6.mirror = true;
      setRotation(Shape6, 0F, 0F, 0F);
      Shape7 = new ModelRenderer(this, 43, 13);
      Shape7.addBox(0F, 0F, 0F, 2, 1, 1);
      Shape7.setRotationPoint(0F, 1F, -6F);
      Shape7.setTextureSize(64, 32);
      Shape7.mirror = true;
      setRotation(Shape7, 0F, 0F, 0F);
      Shape8 = new ModelRenderer(this, 43, 15);
      Shape8.addBox(0F, 0F, 0F, 8, 1, 1);
      Shape8.setRotationPoint(-3F, 3F, -6F);
      Shape8.setTextureSize(64, 32);
      Shape8.mirror = true;
      setRotation(Shape8, 0F, 0F, 0F);
      Shape9 = new ModelRenderer(this, 32, 0);
      Shape9.addBox(-0.5F, 0F, 0F, 1, 1, 6);
      Shape9.setRotationPoint(-2F, 3F, -5F);
      Shape9.setTextureSize(64, 32);
      Shape9.mirror = true;
      setRotation(Shape9, 0F, 0.5235988F, 0F);
      Shape10 = new ModelRenderer(this, 32, 0);
      Shape10.addBox(-0.5F, 0F, 0F, 1, 1, 6);
      Shape10.setRotationPoint(4F, 3F, -5F);
      Shape10.setTextureSize(64, 32);
      Shape10.mirror = true;
      setRotation(Shape10, 0F, -0.5235988F, 0F);
      Shape11 = new ModelRenderer(this, 32, 18);
      Shape11.addBox(0F, 0F, 0F, 3, 3, 8);
      Shape11.setRotationPoint(3F, 6F, -4F);
      Shape11.setTextureSize(64, 32);
      Shape11.mirror = true;
      setRotation(Shape11, 0F, 0F, 0F);
  }
  
  public void render(Entity par1Entity, float par2, float par3, float par4, float par5, float par6, float par7)
  {
      this.setRotationAngles(par2, par3, par4, par5, par6, par7, par1Entity);
    Shape1.render(par7);
    Shape2.render(par7);
    Shape3.render(par7);
    Shape4.render(par7);
    Shape5.render(par7);
    Shape6.render(par7);
    Shape7.render(par7);
    Shape8.render(par7);
    Shape9.render(par7);
    Shape10.render(par7);
    Shape11.render(par7);
  }
  
  private void setRotation(ModelRenderer model, float x, float y, float z)
  {
    model.rotateAngleX = x;
    model.rotateAngleY = y;
    model.rotateAngleZ = z;
  }
  
  public void setRotationAngles(float par1, float par2, float par3, float par4, float par5, float par6, Entity par7Entity)
  {
	  this.Shape3.rotateAngleY = par4 / (180F / (float)Math.PI);
      this.Shape3.rotateAngleX = par5 / (180F / (float)Math.PI);
  }

}
